server:
  port: 8081
spring:
  application:
    name: secure-order-service
  security:
    user:
      name: user
      password: 12345
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root
    password: root@1234
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:12345@localhost:8761/eureka