eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 0
spring:
  application:
    name: coupon-ws
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/hr
    username: root
    password: root@1234
  jpa:
    #hibernate:
     # ddl-auto: create
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:9411