server:
  port: 8761
spring:
  application:
    name: secure-eureka-server
  security:
    user:
      name: admin
      password: 12345
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:12345@localhost:8761/eureka
