server:
  port: 8082
spring:
  application:
    name: order-service
  h2:
    console:
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
