eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
server:
  port: 0
spring:
  application:
    name: product-ws
  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/playbook
  boot:
    admin:
      client:
        url: http://localhost:9410
